name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      TESTING_ADDRESS: ${{ secrets.TESTING_ADDRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Print env variables
        run: |
          echo "API_KEY is set to: $API_KEY"
          echo "TESTING_ADDRESS is set to: $TESTING_ADDRESS"

      - name: Check env variables
        run: |
          if [ -z "$API_KEY" ]; then echo "API_KEY is not set"; else echo "API_KEY is set"; fi
          if [ -z "$TESTING_ADDRESS" ]; then echo "TESTING_ADDRESS is not set"; else echo "TESTING_ADDRESS is set"; fi

      - name: Run integration tests
        run: npm run test:integration
