name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: $${{ secrets.API_KEY}}
      TESTING_ADDRESS: 0xdFd1656602DB564661522daAd0ADB0b98d581050
      # TESTING_ADDRESS: $${{ secrets.TESTING_ADDRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Print env variables
        run: printenv | grep API_KEY

      - name: Print testing address
        run: printenv | grep TESTING_ADDRESS

      # - name: Run unit tests
      #   run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration
